---
- name: Configure web service
  hosts: nodes
  tasks:
    - name: remove Apache
      yum:
        name: httpd
        state: absent
    - name: remove index.html
      file:
        path: /var/www/html/index.html
        state: absent
    - name: close web port on firewall
      firewalld:
        service: http
        permanent: yes
        state: disabled
        immediate: yes
